# Generated by Django 4.2.5 on 2024-08-18 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_programmes', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Computer Engineering', 'Computer Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Materials Engineering', 'Materials Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Marine Engineering', 'Marine Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Agric Engineering', 'Agric Engineering')], max_length=200, null=True)),
                ('resource_item', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
