# Generated by Django 4.2.5 on 2024-07-03 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('baseresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps_resources.baseresource')),
                ('resource_item', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            bases=('apps_resources.baseresource',),
        ),
        migrations.CreateModel(
            name='LinkResource',
            fields=[
                ('baseresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps_resources.baseresource')),
                ('resource_item', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('apps_resources.baseresource',),
        ),
        migrations.AddField(
            model_name='baseresource',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseresource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookresource',
            name='resource_item',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='resource_item',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
