# Generated by Django 4.2.5 on 2024-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_resources', '0002_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='mode',
            field=models.CharField(blank=True, choices=[('In-Person', 'In-Person'), ('Online -(Zoom)', 'Online -(Zoom)')], max_length=255, null=True),
        ),
    ]
