# Generated by Django 4.2.5 on 2024-08-19 21:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_resources', '0003_tutorial_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to meeting if Online/Virtual'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='mode',
            field=models.CharField(blank=True, choices=[('In-Person', 'In-Person'), ('Online -(Zoom)', 'Online -(Zoom)')], max_length=255, null=True, verbose_name='Mode of meeting'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Tutorial'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='programme',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Computer Engineering', 'Computer Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Materials Engineering', 'Materials Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Marine Engineering', 'Marine Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Agric Engineering', 'Agric Engineering')], max_length=200, null=True, verbose_name='Related Programmes'),
        ),
    ]
