# Generated by Django 4.2.5 on 2024-07-14 23:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_resources', '0003_baseresource_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresource',
            name='related_programmes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Computer Engineering', 'Computer Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Petroleum Engineering', 'Petroleum Engineering')], max_length=200, null=True),
        ),
    ]
