# Generated by Django 4.2.5 on 2024-08-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_resources', '0004_tutorial_link_alter_tutorial_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
